fields:
  -
    handle: title
    field:
      type: text
      required: true
      validate:
        - required
  -
    handle: api_key
    field:
      input_type: text
      display: 'API Key'
      type: text
      icon: text
      listable: hidden
  -
    handle: forms
    field:
      fields:
        -
          handle: handle
          field:
            input_type: text
            display: Handle
            type: text
            icon: text
            width: 33
            listable: hidden
        -
          handle: name_field
          field:
            input_type: text
            display: 'Name Field'
            type: text
            icon: text
            width: 33
            listable: hidden
        -
          handle: first_name_field
          field:
            input_type: text
            display: 'First Name Field'
            type: text
            icon: text
            width: 33
            listable: hidden
        -
          handle: last_name_field
          field:
            input_type: text
            display: 'Last Name Field'
            type: text
            icon: text
            width: 33
            listable: hidden
        -
          handle: email_field
          field:
            input_type: text
            display: 'Email Field'
            type: text
            icon: text
            width: 33
            listable: hidden
        -
          handle: content_field
          field:
            input_type: text
            display: 'Content Field'
            type: text
            icon: text
            width: 33
            listable: hidden
      mode: table
      reorderable: false
      display: Forms
      type: grid
      icon: grid
      listable: hidden
