name: Mailchimp
version: 1.3.3
description: Subscribes a registering user to a Mailchimp list
url: https://github.com/edalzell/mailchimp
developer: Erin Dalzell
developer_url: https://silentzconsulting.com
