fields:
  mailchimp_key:
    type: text
    validate: required
  forms:
    type: grid
    display: Forms
    fields:
      mailchimp_list_id:
        type: text
        display: 'Mailchimp List ID'
        validate: required
      form_and_field:
        type: mailchimp
        display: 'Form & Permission Field'
        instructions: null
        validate: required
    mode: table
    min_rows: "1"
    add_row: Add Form